# Taken from github.com/rymaju

name: Build & Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.7
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: '8.4'
      
      - name: Install Pollen
        run: raco pkg install --no-docs --auto pollen
          
      - name: Build and Publish Pollen Source Files
        run: > 
          mkdir -p build/small-rust-os build/blog &&
          raco pollen render src src/small-rust-os src/blog &&
          raco pollen publish src build &&
          raco pollen publish src/small-rust-os build/small-rust-os &&
          raco pollen publish src/blog build/blog

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: build
